#!/bin/zsh

cd ~/primes/PRIMES13
ant
cd ..
cp PRIMES13/dist/PRIMES13.jar . -f

elemCount=1000
for x in 1 10 20 30 40 50 60 70 80; do
    sudo =set-cpus -n $x seq > /dev/null 2>&1
    for (( n = 0; n < 8; n++ )); do
        pl java -Xms128G -Xmx128G -jar PRIMES13.jar 1 $x $elemCount
        elemCount=$[elemCount * 10]
    done
done
