#!/home/am6/mpdev/bin/pl /bin/zsh

ant

multiplier=0

if [ $1 = "tom" ]; then
	multiplier=6
else
	multiplier=10
fi

sudo =set-cpus -n 1 seq > /dev/null 2>&1
for (( n = 10; n <= 10000000; n = n * 10 )); do
    java -Xms128G -Xmx128G -jar PRIMES13.jar 1 $n $2
done


for (( x = 1; x <= 8; x++ )); do
    sudo =set-cpus -n $[x*multiplier] seq > /dev/null 2>&1
    for (( n = 10; n <= 10000000; n = n * 10 )); do
        java -XX:+UseG1GC -Xms128G -Xmx128G -jar PRIMES13.jar $[x*multiplier] $n $2
    done
done
