#!/home/am6/mpdev/bin/pl /bin/zsh

ant
cp dist/PRIMES13.jar . -f

for x in 1 10 20 30 40 50 60 70 80; do
    sudo =set-cpus -n $x seq > /dev/null 2>&1
    for (( n = 10; n <= 10000000; n = n * 10 )); do
        java -Xms128G -Xmx128G -jar PRIMES13.jar 1 $x $n
    done
done


TRAPEXIT() {
	sudo =set-cpus all > /dev/null 2>&1
}
